Fix pgvector work with the tutorial
- Fix `long_text` KeyError
- Fix `psycopg2.errors.UndefinedFunction: operator does not exist: vector <=> numeric[]` when `include_similarity=True`
- Fix `TypeError: PgVectorRM.forward() got an unexpected keyword argument 'k'` in the forward method